notifications:
  email:
    on_success: never
    on_failure: change
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive
script:
  - sudo apt-get moo; make install && make clean

