notifications:
  email:
    on_success: never
    on_failure: change
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: required
before_install:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get update -qq; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq texlive; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew install g++; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" -e 's/-static//g' Makefile; fi
script:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get moo; fi
  - make install && make clean

