notifications:
  email:
    on_success: never
    on_failure: change
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: required
if [ ${TRAVIS_OS_NAME} == linux ]; then
  before_install: sudo apt-get update -qq && sudo apt-get install -qq texlive
fi
if [ ${TRAVIS_OS_NAME} == osx ]; then
  before_script: sed -i -e 's/-static//g' Makefile
fi
script:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then
      sudo apt-get moo
    fi
  - make install && make clean

