#Linux build
notifications:
  email:
    on_success: never
    on_failure: change
language: cpp
compiler:
  - clang
  - gcc
os: linux
dist: trusty
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive
  - sudo apt-get moo
script: make install && make clean

#Mac build
