notifications:
  email:
    on_success: never
    on_failure: change
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - texlive
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
before_install:
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" -e 's/-static//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew outdated gcc48 || brew upgrade gcc48; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then alias g++='g++-4.8'; fi
script:
  - make install
  - make clean
  - if [ ${TRAVIS_OS_NAME} == linux ]; then apt-get moo; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew beer; fi
