#Build testing for LICHEM

#NB: Currently the OSX build is only for a serial binary

#Email settings
notifications:
  email:
    on_success: never
    on_failure: change

#Compiler settings
language: cpp
compiler:
  - clang
  - gcc

#OS settings
sudo: required
dist: trusty
os:
  - linux
  - osx

#Install required packages
before_install:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get update -qq; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq texlive; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" -e 's/-static//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" -e 's/-fopenmp//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" -e 's/SEDI=-i/SEDI=-i \"\" -e/g' Makefile; fi

#Run tests
script:
  - make install && make clean
  - if [ ${TRAVIS_OS_NAME} == linux ]; then apt-get moo; fi
